version: '3'
services:
  app:
    container_name: greenlock-express-test
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./greenlock.d:/usr/src/app/greenlock.d
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongodb_docker2
    image: mongo
    ports:
      - '127.0.0.1:27017:27017'
